# Generated by Django 5.1.7 on 2025-09-15 03:52

import django.db.models.deletion
import viewer.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0007_worklog_edited_time_worklog_entered_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255)),
                ('view_date', models.DateField()),
                ('image_360', models.ImageField(upload_to='viewer/360_images/', validators=[viewer.validators.validate_360_image])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_entries', to='project.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_entries', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-view_date'],
            },
        ),
    ]
