# Generated by Django 5.1.7 on 2025-09-15 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_worklog_edited_time_worklog_entered_time'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(blank=True, help_text='Custom or auto-generated key to share viewer access.', max_length=100, unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'unique_together': {('organisation', 'project')},
            },
        ),
    ]
