# Generated by Django 5.1.7 on 2025-09-18 13:06

import viewer.models
import viewer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_projectaccesskey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectaccesskey',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='image_360',
            field=models.ImageField(upload_to=viewer.models.unique_filename, validators=[viewer.validators.validate_360_image]),
        ),
    ]
