# Generated by Django 5.1.7 on 2025-09-20 06:51

import django.db.models.deletion
import viewer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_worklog_edited_time_worklog_entered_time'),
        ('viewer', '0003_alter_projectaccesskey_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='project.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='project.project')),
            ],
            options={
                'unique_together': {('name', 'organisation', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ViewerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255)),
                ('view_date', models.DateField()),
                ('file', models.FileField(help_text='SVG file for viewing', upload_to=viewer.models.svg_file_upload)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_files', to='project.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_files', to='project.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='viewer_files', to='viewer.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-view_date'],
            },
        ),
    ]
