# Generated by Django 5.1.7 on 2025-09-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_tag_viewerfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewerfile',
            name='title',
        ),
    ]
