# Generated by Django 5.1.7 on 2025-04-08 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'verbose_name': 'Work Log', 'verbose_name_plural': 'Work Logs'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Work Type', 'verbose_name_plural': 'Work Types'},
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.worktype', verbose_name='Work Type'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Work Type'),
        ),
    ]
