# Generated by Django 5.1.7 on 2025-04-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_worklog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_stage',
            field=models.CharField(choices=[('1', 'Stage 1'), ('2', 'Stage 2'), ('3', 'Stage 3'), ('4', 'Stage 4'), ('5', 'Stage 5')], default='1', max_length=1, verbose_name='Current Stage'),
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Deliverable Name')),
                ('stage', models.CharField(choices=[('1', 'Stage 1'), ('2', 'Stage 2'), ('3', 'Stage 3'), ('4', 'Stage 4'), ('5', 'Stage 5')], max_length=1, verbose_name='Stage')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('ready', 'Ready for Validation'), ('passed', 'Passed Validation'), ('failed', 'Failed Validation'), ('discrepancy', 'Site Discrepancy')], default='not_started', max_length=20, verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
            ],
            options={
                'verbose_name': 'Deliverable',
                'verbose_name_plural': 'Deliverables',
                'unique_together': {('project', 'name', 'stage')},
            },
        ),
    ]
