# Generated by Django 5.1.7 on 2025-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_current_stage_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
