# Generated by Django 5.1.7 on 2025-04-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_deliverable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliverable',
        ),
    ]
