services:
  web:
    build: .
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn webdjango.wsgi:application --bind unix:/tmp/gunicorn.sock
      "
    volumes:
      - .:/app
      - /var/www/modelflick/static:/var/www/modelflick/static
      - ./media:/app/media
      - /tmp:/tmp
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - PYTHONUNBUFFERED=1
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
