services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./media:/app/media   # <-- Change this line from media_volume to bind mount
    env_file:
      - .env
    environment:
      - DEBUG=1
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:   # you can delete this since you are not using it now


  # docker-compose -f docker-compose.dev.yml up --build -d
