services:
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && gunicorn webdjango.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles  # Mount the staticfiles directory to container
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
