# Generated by Django 5.1.7 on 2025-04-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': 'Fee Entry', 'verbose_name_plural': 'Fee Entries'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Promo Code', 'verbose_name_plural': 'Promo Codes'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='base_fee_per_sqft',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Fee per Sq.Ft'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.promocode', verbose_name='Associated Promo Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Promo Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount (%)'),
        ),
    ]
