# Generated by Django 5.1.7 on 2025-07-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_convert_promo_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='consultant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='base_fee_per_sqft',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
