# Generated by Django 5.1.7 on 2025-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_fee_consultant_fee_designation_fee_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
