# Generated by Django 5.1.7 on 2025-04-26 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='project',
        ),
        migrations.AlterField(
            model_name='worklog',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.deliverable', verbose_name='Deliverable'),
        ),
    ]
