# Generated by Django 5.1.7 on 2025-05-12 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_worklog_project_alter_worklog_deliverable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_deliverables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member'), ('client', 'Client')], max_length=20),
        ),
    ]
