# Generated by Django 5.1.7 on 2025-06-30 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='edited_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Edited Time'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='entered_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Record Time'),
        ),
    ]
